# Generated by Django 5.0.4 on 2025-02-20 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_alter_student_gender'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'verbose_name': '学生信息', 'verbose_name_plural': '学生信息'},
        ),
        migrations.AlterModelTable(
            name='student',
            table='student',
        ),
    ]
