# Generated by Django 5.0.4 on 2025-03-13 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_alter_student_options_alter_student_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='gender',
            field=models.CharField(choices=[('F', '女'), ('M', '男')], max_length=1, verbose_name='性别'),
        ),
    ]
